name: Build and Scan

on:
  push:
  pull_request:

jobs:
  build:
    runs_on: ubuntu-20.4
    steps:
      - name: Check out code 
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm clean-install
